package com.lokiscale.loomspan.internal.provider;

public enum ProviderFailureCategory
{
    CONNECTIVITY, TIMEOUT, RATE_LIMITED, PROVIDER_OVERLOADED, PROVIDER_UNAVAILABLE,
    SERVER_ERROR, AUTHENTICATION, AUTHORIZATION, PAYMENT_REQUIRED, INVALID_REQUEST,
    CONTEXT_LIMIT, CONTENT_POLICY, CLIENT_DECODING, UNKNOWN
}
