package com.lokiscale.loomspan.internal.runtime.observation;

public enum ExecutionActivityKind
{
    TRACE_STARTED,
    FRAME_OPENED,
    FRAME_CLOSED,
    MODEL_REQUEST_SENT,
    MODEL_RESPONSE_RECEIVED,
    MODEL_ATTEMPT_FAILED,
    PLAN_CREATED,
    PLAN_UPDATED,
    PLAN_VALIDATION_FAILED,
    PLAN_RETRY_REQUESTED,
    TOOL_CALL_STARTED,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_FAILED,
    STEP_STARTED,
    STEP_ACTION_REJECTED,
    STEP_COMPLETED,
    ERROR_RECORDED,
    TRACE_COMPLETED,
    EXECUTION_OBSERVATION_ENDED
}
